hm04
Shpuntoff/nodejs-homework-rest-api pull request #3
Opened 2023-02-16 21:32 UTC by Shpuntoff

Проверьте пожалуйста

2023-02-17 19:34 UTC, Eastvarga requested changes
Є зауваження

2023-02-17 19:34 UTC, Eastvarga commented on controllers/usersConrollers/login.js
> +
Валідацію треба винести до окремого мідлвару валідації, та використовувати перед контроллером у рауті

2023-02-17 19:34 UTC, Eastvarga commented on controllers/usersConrollers/logout.js
> +        }
З чого це тут ця помилка? Пере раутом потрібен мідлвар авторизаціїї котрий подібні помилки кидає а у контроллері ви лише занулюєте токен юзера тим самим вилогінюєте його

2023-02-17 19:34 UTC, Eastvarga commented on controllers/usersConrollers/register.js
> +        };
Валідацію слід використовувати окремо віж контроллера, перед контроллером

2023-02-17 19:34 UTC, Eastvarga commented on middleware/authenticate.js
> +        if (bearer !== "Bearer"){
токен слід перевіряти бо він може бути не визначеним

2023-02-17 19:34 UTC, Eastvarga commented on routes/api/auth.js
> +router.post("/signup", register);
router.post("/signup", **validateRegisterDto**, register); ось так мідлвар валідації квикористовується перед контроллером

2023-02-17 19:34 UTC, Eastvarga commented on routes/api/contacts.js
>  router.get("/:contactId", getById);
authenticate повинно бути на всіх раутах контактів

2023-02-18 08:56 UTC, Shpuntoff commented
зробив коміт з фіксами

2023-02-19 06:19 UTC, merged